// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package forms

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CreateCategory() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"card bg-base-100 w-full max-w-lg mx-auto shadow-xl border border-base-300\"><div class=\"card-body\"><h2 class=\"card-title text-xl font-bold mb-4\">Créer une nouvelle catégorie</h2><div class=\"card bg-base-100 w-full max-w-lg mx-auto shadow-xl border border-base-300\"><div class=\"card-body\"><h2 class=\"card-title mb-4\">Créer une catégorie</h2><form hx-post=\"/createCategory\" hx-encoding=\"multipart/form-data\" hx-target=\"#res2\" hx-swap=\"innerHTML\" class=\"space-y-4\"><div class=\"form-control w-full\"><label class=\"label\"><span class=\"label-text\">Nom de la catégorie</span></label> <input type=\"text\" name=\"CategoryName\" placeholder=\"ex: Micro-contrôleurs\" class=\"input input-bordered w-full\" required minlength=\"2\" maxlength=\"150\"></div><div class=\"form-control w-full\"><label class=\"label\"><span class=\"label-text\">Image de la catégorie</span></label> <input type=\"file\" name=\"Image\" accept=\"image/*\" class=\"file-input file-input-bordered file-input-primary w-full\" required></div><button type=\"submit\" class=\"btn btn-primary w-full mt-4\">Créer la catégorie</button></form><div id=\"res2\"></div></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
