// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package forms

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"crow/help/strs"
	"fmt"
	"strings"
)

func Users(users []strs.User) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"w-full max-w-4xl mx-auto space-y-3 p-4\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for i, u := range users {
			if u.UserId != 1 && u.UserId != 2 {
				templ_7745c5c3_Err = userAccordion(u, i == 0).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func userAccordion(u strs.User, isFirst bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"collapse bg-base-100 border border-base-300 rounded-box shadow-sm\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isFirst {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<input type=\"radio\" name=\"user-accordion\" checked=\"checked\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<input type=\"radio\" name=\"user-accordion\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<!-- Accordion Header --><div class=\"collapse-title font-semibold flex items-center justify-between pr-8\"><div class=\"flex items-center gap-3\"><span class=\"text-base-content font-bold\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(u.UserName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/mark/comp/forms/users.templ`, Line: 30, Col: 70}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</span></div></div><!-- Accordion Body --><div class=\"collapse-content text-sm space-y-6 pt-2\"><!-- SECTION 1: Update Username & Access Rights --><form hx-post=\"/updateUser\" hx-target-error=\"#res\" hx-swap=\"none\" x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf(`{ 
                    roles: %s, 
                    get accessString() { return this.roles.join(''); } 
                }`, parseRolesArray(u.Access)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/mark/comp/forms/users.templ`, Line: 45, Col: 46}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" class=\"space-y-4 pt-2 border-t border-base-200\"><input type=\"hidden\" name=\"UserId\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("%d", u.UserId))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/mark/comp/forms/users.templ`, Line: 48, Col: 86}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\"><div class=\"form-control w-full\"><label class=\"label pb-1.5\"><span class=\"label-text font-medium\">Nom d'utilisateur</span></label> <input type=\"text\" name=\"UserName\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(u.UserName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/mark/comp/forms/users.templ`, Line: 57, Col: 42}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" class=\"input input-bordered input-sm w-full\" required minlength=\"3\" maxlength=\"50\"></div><!-- Access Rights (cmd) --><div class=\"form-control w-full\"><label class=\"label pb-1.5\"><span class=\"label-text font-medium\">Droits d'accès</span></label><div class=\"flex flex-col md:flex-row gap-3 flex-wrap justify-around bg-base-200 p-3 rounded-lg\"><label class=\"label cursor-pointer justify-start gap-2\"><input type=\"checkbox\" value=\"c\" x-model=\"roles\" class=\"checkbox checkbox-primary checkbox-sm\"> <span class=\"label-text\">Créer (c)</span></label> <label class=\"label cursor-pointer justify-start gap-2\"><input type=\"checkbox\" value=\"m\" x-model=\"roles\" class=\"checkbox checkbox-primary checkbox-sm\"> <span class=\"label-text\">Modifier (m)</span></label> <label class=\"label cursor-pointer justify-start gap-2\"><input type=\"checkbox\" value=\"d\" x-model=\"roles\" class=\"checkbox checkbox-primary checkbox-sm\"> <span class=\"label-text\">Supprimer (d)</span></label></div><input type=\"hidden\" name=\"Access\" :value=\"accessString\"></div><div class=\"flex justify-end pt-1\"><button type=\"submit\" class=\"btn btn-primary btn-sm\">Mettre à jour le profil</button></div></form><div class=\"divider my-0\">Changer le mot de passe</div><!-- SECTION 2: Update Password with 12-char limit warning --><form hx-post=\"/updateUserPassword\" hx-target-error=\"#res\" hx-swap=\"none\" x-data=\"{ pass: '' }\" @htmx:after-request=\"if (detail.successful) { pass = ''; }\" class=\"space-y-4\"><input type=\"hidden\" name=\"UserId\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf("%d", u.UserId))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/mark/comp/forms/users.templ`, Line: 124, Col: 86}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\"><div class=\"form-control w-full\"><label class=\"label pb-1.5\"><span class=\"label-text font-medium my-3 text-xs md:text-sm\">Nouveau mot de passe (6-12 caractères)</span></label><div class=\"flex flex-col md:flex-row items-center gap-3\"><input type=\"password\" name=\"Password\" x-model=\"pass\" placeholder=\"••••••••\" class=\"input input-bordered input-sm grow\" required minlength=\"6\" maxlength=\"12\"> <button type=\"submit\" class=\"btn btn-neutral btn-outline btn-sm shrink-0\">Modifier le mot de passe</button></div><div x-show=\"pass.length >= 12\" x-cloak class=\"label pb-0 pt-1\"><span class=\"label-text-alt text-warning font-medium\">⚠️ Limite maximale de 12 caractères atteinte</span></div></div></form><!-- SECTION 3: Account Deletion --><div class=\"pt-4 border-t border-base-200 flex justify-end\"><div x-data=\"{ confirm: false }\"><button type=\"button\" x-show=\"!confirm\" @click=\"confirm = true\" class=\"btn btn-error btn-outline btn-sm\">Supprimer le compte</button> <button type=\"button\" x-show=\"confirm\" x-cloak @click=\"confirm = false\" hx-post=\"/deleteUser\" hx-vals=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var8 string
		templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.ResolveAttributeValue(fmt.Sprintf(`{"userId": "%d"}`, u.UserId))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/mark/comp/forms/users.templ`, Line: 169, Col: 75}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "\" hx-target=\"closest .collapse\" hx-target-error=\"#res\" hx-swap=\"delete\" class=\"btn btn-accent btn-sm animate-pulse font-bold\">Confirmer la suppression ?</button></div></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func parseRolesArray(access string) string {
	var roles []string
	if strings.Contains(access, "c") {
		roles = append(roles, "'c'")
	}
	if strings.Contains(access, "m") {
		roles = append(roles, "'m'")
	}
	if strings.Contains(access, "d") {
		roles = append(roles, "'d'")
	}
	return "[" + strings.Join(roles, ", ") + "]"
}

var _ = templruntime.GeneratedTemplate
