// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package comp

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"crow/help/strs"
)

func ProjetsMod(user *strs.User) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex justify-center items-center\"><form hx-post=\"/uploadProject\" hx-encoding=\"multipart/form-data\" hx-target=\"#result\" hx-swap=\"innerHTML\" class=\"flex flex-col gap-4 w-full max-w-md\"><div class=\"form-control w-full\"><label class=\"label\" for=\"ProjectName\"><span class=\"label-text\">Project Name</span></label> <input type=\"text\" id=\"ProjectName\" name=\"ProjectName\" class=\"input input-bordered w-full\" minlength=\"2\" maxlength=\"150\" required></div><div class=\"form-control w-full\"><label class=\"label\" for=\"Description\"><span class=\"label-text\">Description</span></label> <textarea id=\"Description\" name=\"Description\" class=\"textarea textarea-bordered w-full h-32\" minlength=\"5\" maxlength=\"5000\" required></textarea></div><div class=\"form-control w-full\"><label class=\"label\" for=\"CategoryId\"><span class=\"label-text\">Category ID</span></label> <input type=\"number\" id=\"CategoryId\" name=\"CategoryId\" class=\"input input-bordered w-full\" value=\"1\" min=\"1\" required></div><div class=\"form-control w-full\"><label class=\"label\" for=\"MImage\"><span class=\"label-text\">Main Image</span></label> <input type=\"file\" id=\"MImage\" name=\"MImage\" class=\"file-input file-input-bordered w-full\" accept=\"image/*\" required></div><div class=\"form-control w-full\"><label class=\"label\" for=\"Images\"><span class=\"label-text\">Gallery Images</span></label> <input type=\"file\" id=\"Images\" name=\"Images\" class=\"file-input file-input-bordered w-full\" accept=\"image/*\" multiple required></div><button type=\"submit\" class=\"btn btn-primary w-full\">Create Project</button><div id=\"result\" class=\"text-white\"></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
